hystrix:
  image: docker4tracy/hystrix-dashboard
  ports:
   - "7979:7979"
  links:
   - gateway
   - discovery
discovery:
  image: docker4tracy/discovery-microservice
  ports:
   - "8761:8761"
configserver:
  image: docker4tracy/config-microservice
  ports:
   - "8888:8888"
  links:
   - discovery
gateway:
  image: docker4tracy/api-gateway-microservice
  ports:
   - "10000:10000"
  links:
   - discovery
   - configserver
   - user
   - movie
   - recommendation
user:
  image: docker4tracy/users-microservice
  links:
   - discovery
   - configserver
movie:
  image: docker4tracy/movie-microservice
  links:
   - discovery
   - configserver
recommendation:
  image: docker4tracy/recommendation-microservice
  links:
   - discovery
   - configserver
moviesui:
  image: docker4tracy/movies-ui
  ports:
     - "9006:9006"
  links:
   - discovery
   - configserver
